version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      nestjs:
        patterns: ['@nestjs/*']
      lint:
        patterns: ['eslint*', '@eslint/*', 'typescript-eslint', 'prettier', '@vitest/eslint-plugin']
      test:
        patterns: ['vitest', '@vitest/*', 'supertest', '@types/supertest', 'mongodb-memory-server']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
