import { randomUUID } from 'node:crypto';

import { InvariantViolationError } from './domain-error.js';

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/**
 * Base class for aggregate identifiers. Identity is generated by the domain (UUID v4),
 * never by the database, so entities are valid before they are persisted.
 */
export abstract class EntityId {
  readonly value: string;

  protected constructor(value: string) {
    if (!UUID_PATTERN.test(value)) {
      throw new InvariantViolationError(`"${value}" is not a valid identifier`, { value });
    }
    this.value = value.toLowerCase();
    Object.freeze(this);
  }

  protected static newValue(): string {
    return randomUUID();
  }

  equals(other: EntityId | null | undefined): boolean {
    return other?.constructor === this.constructor && other.value === this.value;
  }

  toString(): string {
    return this.value;
  }
}
